######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 3 02:56:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += boxing.h game.h glove_png.h pow_png.h smash.h smash_png.h
SOURCES += boxing.cpp game.cpp main.cpp selectsmash.cpp smash.cpp
